name: "Scan Docker Images"
on: 
  push:
    branches:
      - main

jobs:
  AWS:
    name: Despliegue en AWS
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      security-events: write
      actions: read
      contents: read

    steps:
      - name: "Obteniendo código de repositorio"
        uses: actions/checkout@v3

      - name: "Configuración de credenciales en AWS"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN }}
          aws-region: us-east-2

      - name: "Aprovisianamiento con terraform"
        run: |
          cd Terraform
          terraform init
          terraform plan -out tfplan
          terraform apply tfplan >> results_tfplan.txt
          ip_webgoat=$(cat results_tfplan.txt | grep "My_ip = " | awk '{ print $3 }' | sed 's/"//g')
      
      - name: "Ansible"
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          sudo apt update
          sudo apt install -y ansible
          cd Ansible
          echo "$PRIVATE_KEY" >> $HOME/key.pem
          chmod 400 $HOME/key.pem
          cat inventario
          echo ip_webgoat
          sed -i "s/IP/$ip_webgoat/g" inventario
          cat inventario

      - name: "Destruccion de infraestructura"
        run: |
          terraform plan -destroy -out tfplan
          terraform apply tfplan