name: "SCA & SAST"
on: push

jobs:

  SCA:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    
    steps:
      - name: "Obteniendo código de repositorio"
        uses: actions/checkout@v3
      
      - name: "Dependency Check"
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'WebGoat'
          path: '.'
          format: 'SARIF'
          out: 'reports'

      - name: "Carga de reportes para poder descargarlo"
        uses: actions/upload-artifact@master
        with:
           name: SCA Report
           path: reports/dependency-check-report.sarif
      
      - name: "Carga de reporte SCA a GitHub Security"
        uses: github/codeql-action/upload-sarif@v2
        with:
            sarif_file: reports/dependency-check-report.sarif

  SAST:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: "Obteniendo código de repositorio"
        uses: actions/checkout@v3

      - name: "Instalando herramienta SAST"
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest-beta
       
      - name: "Ejecucion herramienta"
        run: horusec start -p="./" -o sarif -O result_SAST.sarif --return-error	true
        continue-on-error: true

      - name: "Carga de reportes para poder descargarlo"
        uses: actions/upload-artifact@master
        with:
           name: SAST Report Horusec
           path: result_SAST.sarif
      
      - name: "Carga de reporte SAST a GitHub Security"
        uses: github/codeql-action/upload-sarif@v2
        with:
            sarif_file: result_SAST.sarif